// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type AppInit struct {
	ID        int64
	CreatedAt time.Time
}

type Link struct {
	ID          int64
	OriginalUrl string
	ShortName   string
	CreatedAt   time.Time
}
